# Generated by Django 6.0.3 on 2026-04-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
