# Generated by Django 6.0.8 on 2026-09-24 09:52

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_add_is_verified_to_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=core.validators.RandomFilename("profiles"),
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "gif", "webp"]
                    ),
                    core.validators.validate_image_size,
                ],
            ),
        ),
    ]
