# Generated by Django 6.0.3 on 2026-04-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_is_verified_to_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True),
        ),
    ]
