# Generated by Django 6.0.8 on 2026-09-24 09:52

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=core.validators.RandomFilename("marketplace"),
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "gif", "webp"]
                    ),
                    core.validators.validate_image_size,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
