# Generated by Django 6.0.3 on 2026-04-13 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cost', models.PositiveIntegerField()),
                ('icon', models.CharField(default='🎁', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('stock', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['cost'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('earn', 'Earned'), ('redeem', 'Redeemed')], max_length=10)),
                ('amount', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_spent', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('claimed', 'Claimed')], default='pending', max_length=10)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('perk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='wallet.perk')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='wallet.wallet')),
            ],
            options={
                'ordering': ['-redeemed_at'],
            },
        ),
    ]
