# Generated by Django 6.0.3 on 2026-04-13 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_type', models.CharField(choices=[('good_samaritan', 'Good Samaritan'), ('trustworthy_seller', 'Trustworthy Seller'), ('top_tutor', 'Top Tutor'), ('active_helper', 'Active Helper'), ('first_post', 'First Post')], max_length=30)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['awarded_at'],
                'unique_together': {('user', 'badge_type')},
            },
        ),
    ]
