# Generated by Django 6.0.8 on 2026-09-23 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0002_add_badge"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="reference",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.UniqueConstraint(
                fields=("wallet", "reference"), name="unique_wallet_reference"
            ),
        ),
    ]
